allowBuilds:
  "@firebase/util": true
  "@google/genai": true
  protobufjs: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - "@firebase/util"
  - "@google/genai"
  - protobufjs
  - sharp
  - unrs-resolver
