import type { CourseLesson } from "@/content/dominate-digital/schema";

/**
 * Real lessons for the modules that have a built simulator so far. Slugs
 * here must exactly match the MOD<n>_LESSON_SLUGS array inside that
 * module's HTML file (public/academy/digital-marketing-ai/module-<n>.html)
 * -- that file writes these same slugs into the shared completed-lessons
 * key once the module is finished, and this list is what the course page
 * and resume card use to compute progress and the next lesson to resume.
 */
export const dominateDigitalLessons: CourseLesson[] = [
  {
    id: "m1-l1",
    slug: "what-is-digital-marketing",
    moduleId: "m1",
    order: 1,
    titleHt: "Kisa Maketing Dijital Ye?",
    titleFr: "Qu'est-ce que le Marketing Digital ?",
    titleEn: "What Is Digital Marketing?",
  },
  {
    id: "m1-l2",
    slug: "digital-vs-traditional-marketing",
    moduleId: "m1",
    order: 2,
    titleHt: "Maketing Dijital kont Maketing Tradisyonèl",
    titleFr: "Marketing Digital vs. Traditionnel",
    titleEn: "Digital vs. Traditional Marketing",
  },
  {
    id: "m1-l3",
    slug: "the-customer-journey",
    moduleId: "m1",
    order: 3,
    titleHt: "Vwayaj Kliyan an",
    titleFr: "Le Parcours Client",
    titleEn: "The Customer Journey",
  },
  {
    id: "m1-l4",
    slug: "the-marketing-funnel",
    moduleId: "m1",
    order: 4,
    titleHt: "Antonwa Maketing an",
    titleFr: "L'Entonnoir de Marketing",
    titleEn: "The Marketing Funnel",
  },
  {
    id: "m1-l5",
    slug: "understanding-value",
    moduleId: "m1",
    order: 5,
    titleHt: "Konprann Valè",
    titleFr: "Comprendre la Valeur",
    titleEn: "Understanding Value",
  },
  {
    id: "m1-l6",
    slug: "myths-about-digital-marketing",
    moduleId: "m1",
    order: 6,
    titleHt: "Manti Yo Di sou Maketing Dijital",
    titleFr: "Mythes sur le Marketing Digital",
    titleEn: "Myths About Digital Marketing",
  },
  {
    id: "m1-l7",
    slug: "careers-in-digital-marketing",
    moduleId: "m1",
    order: 7,
    titleHt: "Karyè nan Maketing Dijital",
    titleFr: "Les Métiers du Marketing Digital",
    titleEn: "Careers in Digital Marketing",
  },
  {
    id: "m2-l1",
    slug: "why-people-really-buy",
    moduleId: "m2",
    order: 1,
    titleHt: "Poukisa Moun Achte Vrèman (Emosyon kont Lojik)",
    titleFr: "Pourquoi les Gens Achètent Vraiment (Émotion contre Logique)",
    titleEn: "Why People Really Buy (Emotion vs. Logic)",
  },
  {
    id: "m2-l2",
    slug: "building-trust",
    moduleId: "m2",
    order: 2,
    titleHt: "Bati Konfyans",
    titleFr: "Bâtir la Confiance",
    titleEn: "Building Trust",
  },
  {
    id: "m2-l3",
    slug: "social-proof",
    moduleId: "m2",
    order: 3,
    titleHt: "Prèv Sosyal",
    titleFr: "Preuve Sociale",
    titleEn: "Social Proof",
  },
  {
    id: "m2-l4",
    slug: "scarcity",
    moduleId: "m2",
    order: 4,
    titleHt: "Rarete",
    titleFr: "Rareté",
    titleEn: "Scarcity",
  },
  {
    id: "m2-l5",
    slug: "authority",
    moduleId: "m2",
    order: 5,
    titleHt: "Otorite",
    titleFr: "Autorité",
    titleEn: "Authority",
  },
  {
    id: "m2-l6",
    slug: "reciprocity",
    moduleId: "m2",
    order: 6,
    titleHt: "Reprosite",
    titleFr: "Réciprocité",
    titleEn: "Reciprocity",
  },
  {
    id: "m2-l7",
    slug: "pricing-psychology",
    moduleId: "m2",
    order: 7,
    titleHt: "Sikoloji Pri",
    titleFr: "Psychologie des Prix",
    titleEn: "Pricing Psychology",
  },
  {
    id: "m2-l8",
    slug: "color-psychology",
    moduleId: "m2",
    order: 8,
    titleHt: "Sikoloji Koulè",
    titleFr: "Psychologie des Couleurs",
    titleEn: "Color Psychology",
  },
  {
    id: "m3-l1",
    slug: "naming-your-business",
    moduleId: "m3",
    order: 1,
    titleHt: "Bay Biznis Ou Yon Non",
    titleFr: "Nommer Votre Entreprise",
    titleEn: "Naming Your Business",
  },
  {
    id: "m3-l2",
    slug: "positioning",
    moduleId: "m3",
    order: 2,
    titleHt: "Pozisyone (Sa ki Fè w Diferan)",
    titleFr: "Positionnement (Ce qui Vous Différencie)",
    titleEn: "Positioning (What Makes You Different)",
  },
  {
    id: "m3-l3",
    slug: "logo-design-basics",
    moduleId: "m3",
    order: 3,
    titleHt: "Baz Konsepsyon Logo",
    titleFr: "Les Bases du Design de Logo",
    titleEn: "Logo Design Basics",
  },
  {
    id: "m3-l4",
    slug: "choosing-your-brand-colors",
    moduleId: "m3",
    order: 4,
    titleHt: "Chwazi Koulè Mak Ou",
    titleFr: "Choisir les Couleurs de Votre Marque",
    titleEn: "Choosing Your Brand Colors",
  },
  {
    id: "m3-l5",
    slug: "typography-for-your-brand",
    moduleId: "m3",
    order: 5,
    titleHt: "Tipografi pou Mak Ou",
    titleFr: "Typographie pour Votre Marque",
    titleEn: "Typography for Your Brand",
  },
  {
    id: "m3-l6",
    slug: "brand-voice",
    moduleId: "m3",
    order: 6,
    titleHt: "Vwa Mak Ou",
    titleFr: "Voix de Marque",
    titleEn: "Brand Voice",
  },
  {
    id: "m3-l7",
    slug: "brand-personality",
    moduleId: "m3",
    order: 7,
    titleHt: "Pèsonalite Mak Ou",
    titleFr: "Personnalité de Marque",
    titleEn: "Brand Personality",
  },
  {
    id: "m3-l8",
    slug: "consistency-across-everything",
    moduleId: "m3",
    order: 8,
    titleHt: "Konsistans nan Tout Bagay",
    titleFr: "Cohérence Partout",
    titleEn: "Consistency Across Everything",
  },
  {
    id: "m4-l1",
    slug: "building-a-customer-avatar",
    moduleId: "m4",
    order: 1,
    titleHt: "Bati yon Avata Kliyan",
    titleFr: "Construire un Avatar Client",
    titleEn: "Building a Customer Avatar",
  },
  {
    id: "m4-l2",
    slug: "finding-pain-points",
    moduleId: "m4",
    order: 2,
    titleHt: "Jwenn Pwen Fristrasyon",
    titleFr: "Trouver les Points de Friction",
    titleEn: "Finding Pain Points",
  },
  {
    id: "m4-l3",
    slug: "understanding-customer-goals",
    moduleId: "m4",
    order: 3,
    titleHt: "Konprann Objektif Kliyan",
    titleFr: "Comprendre les Objectifs du Client",
    titleEn: "Understanding Customer Goals",
  },
  {
    id: "m4-l4",
    slug: "handling-common-objections",
    moduleId: "m4",
    order: 4,
    titleHt: "Jere Objeksyon Komen",
    titleFr: "Gérer les Objections Courantes",
    titleEn: "Handling Common Objections",
  },
  {
    id: "m4-l5",
    slug: "market-research-basics",
    moduleId: "m4",
    order: 5,
    titleHt: "Baz Rechèch Mache",
    titleFr: "Bases de l'Étude de Marché",
    titleEn: "Market Research Basics",
  },
  {
    id: "m4-l6",
    slug: "competitor-research",
    moduleId: "m4",
    order: 6,
    titleHt: "Rechèch Konkirans",
    titleFr: "Recherche sur la Concurrence",
    titleEn: "Competitor Research",
  },
  {
    id: "m4-l7",
    slug: "your-customer-profile",
    moduleId: "m4",
    order: 7,
    titleHt: "Mete Tout Bagay Ansanm: Pwofil Kliyan Ou",
    titleFr: "Tout Assembler : Votre Profil Client",
    titleEn: "Putting It All Together: Your Customer Profile",
  },
  {
    id: "m5-l1",
    slug: "writing-headlines-that-get-read",
    moduleId: "m5",
    order: 1,
    titleHt: "Ekri Tit ki Li",
    titleFr: "Écrire des Titres qu'on Lit",
    titleEn: "Writing Headlines That Get Read",
  },
  {
    id: "m5-l2",
    slug: "hooks-earning-the-next-sentence",
    moduleId: "m5",
    order: 2,
    titleHt: "Kwochè: Genyen Pwochen Fraz la",
    titleFr: "Accroches : Gagner la Phrase Suivante",
    titleEn: "Hooks: Earning the Next Sentence",
  },
  {
    id: "m5-l3",
    slug: "storytelling-in-marketing",
    moduleId: "m5",
    order: 3,
    titleHt: "Naratif nan Maketing",
    titleFr: "La Narration en Marketing",
    titleEn: "Storytelling in Marketing",
  },
  {
    id: "m5-l4",
    slug: "writing-product-descriptions-that-sell",
    moduleId: "m5",
    order: 4,
    titleHt: "Ekri Deskripsyon Pwodwi ki Vann",
    titleFr: "Écrire des Descriptions de Produits qui Vendent",
    titleEn: "Writing Product Descriptions That Sell",
  },
  {
    id: "m5-l5",
    slug: "calls-to-action-ctas",
    moduleId: "m5",
    order: 5,
    titleHt: "Apèl a Aksyon (CTA)",
    titleFr: "Appels à l'Action (CTA)",
    titleEn: "Calls to Action (CTAs)",
  },
  {
    id: "m5-l6",
    slug: "landing-pages-and-sales-pages",
    moduleId: "m5",
    order: 6,
    titleHt: "Paj Aterisaj ak Paj Vant",
    titleFr: "Pages de Destination et de Vente",
    titleEn: "Landing Pages & Sales Pages",
  },
  {
    id: "m5-l7",
    slug: "email-copy",
    moduleId: "m5",
    order: 7,
    titleHt: "Tèks Imèl",
    titleFr: "Texte d'Email",
    titleEn: "Email Copy",
  },
  {
    id: "m6-l1",
    slug: "meet-the-editor",
    moduleId: "m6",
    order: 1,
    titleHt: "Rankontre Editè a",
    titleFr: "Découvrir l'Éditeur",
    titleEn: "Meet the Editor",
  },
  {
    id: "m6-l2",
    slug: "visual-hierarchy",
    moduleId: "m6",
    order: 2,
    titleHt: "Yerarchi Vizyèl",
    titleFr: "Hiérarchie Visuelle",
    titleEn: "Visual Hierarchy",
  },
  {
    id: "m6-l3",
    slug: "composition-and-layout",
    moduleId: "m6",
    order: 3,
    titleHt: "Konpozisyon ak Aranjman",
    titleFr: "Composition et Mise en Page",
    titleEn: "Composition & Layout",
  },
  {
    id: "m6-l4",
    slug: "designing-a-social-media-graphic",
    moduleId: "m6",
    order: 4,
    titleHt: "Fè yon Grafik Rezo Sosyal",
    titleFr: "Créer un Graphique pour les Réseaux Sociaux",
    titleEn: "Designing a Social Media Graphic",
  },
  {
    id: "m6-l5",
    slug: "carousels",
    moduleId: "m6",
    order: 5,
    titleHt: "Karisèl",
    titleFr: "Carrousels",
    titleEn: "Carousels",
  },
  {
    id: "m6-l6",
    slug: "infographics",
    moduleId: "m6",
    order: 6,
    titleHt: "Enfografik",
    titleFr: "Infographies",
    titleEn: "Infographics",
  },
  {
    id: "m6-l7",
    slug: "brand-kits",
    moduleId: "m6",
    order: 7,
    titleHt: "Kit Mak",
    titleFr: "Kit de Marque",
    titleEn: "Brand Kits",
  },
  {
    id: "m7-l1",
    slug: "why-video-works",
    moduleId: "m7",
    order: 1,
    titleHt: "Poukisa Videyo Mache",
    titleFr: "Pourquoi la Vidéo Fonctionne",
    titleEn: "Why Video Works",
  },
  {
    id: "m7-l2",
    slug: "short-form-video-shorts-reels-tiktok",
    moduleId: "m7",
    order: 2,
    titleHt: "Videyo Kout: Shorts, Reels, TikTok",
    titleFr: "Vidéo Courte : Shorts, Reels, TikTok",
    titleEn: "Short-Form Video: Shorts, Reels, TikTok",
  },
  {
    id: "m7-l3",
    slug: "youtube-long-form-video-basics",
    moduleId: "m7",
    order: 3,
    titleHt: "YouTube: Baz Videyo Long",
    titleFr: "YouTube : Bases de la Vidéo Longue",
    titleEn: "YouTube: Long-Form Video Basics",
  },
  {
    id: "m7-l4",
    slug: "writing-a-video-script",
    moduleId: "m7",
    order: 4,
    titleHt: "Ekri yon Script Videyo",
    titleFr: "Écrire un Script Vidéo",
    titleEn: "Writing a Video Script",
  },
  {
    id: "m7-l5",
    slug: "hooks-for-video",
    moduleId: "m7",
    order: 5,
    titleHt: "Kwochè pou Videyo",
    titleFr: "Accroches pour la Vidéo",
    titleEn: "Hooks for Video",
  },
  {
    id: "m7-l6",
    slug: "retention-keeping-people-watching",
    moduleId: "m7",
    order: 6,
    titleHt: "Retansyon: Kenbe Moun ap Gade",
    titleFr: "Rétention : Garder les Gens à l'Écoute",
    titleEn: "Retention: Keeping People Watching",
  },
  {
    id: "m7-l7",
    slug: "thumbnails-that-get-clicks",
    moduleId: "m7",
    order: 7,
    titleHt: "Miniati ki Fè Moun Klike",
    titleFr: "Miniatures qui Font Cliquer",
    titleEn: "Thumbnails That Get Clicks",
  },
  {
    id: "m8-l1",
    slug: "meet-the-ai-chat-tool",
    moduleId: "m8",
    order: 1,
    titleHt: "Rankontre Zouti Chat IA a",
    titleFr: "Découvrir l'Outil de Chat IA",
    titleEn: "Meet the AI Chat Tool",
  },
  {
    id: "m8-l2",
    slug: "prompt-engineering-writing-prompts-that-work",
    moduleId: "m8",
    order: 2,
    titleHt: "Enjenyri Pwonp: Ekri Pwonp ki Mache",
    titleFr: "Ingénierie de Prompt : Écrire des Prompts qui Marchent",
    titleEn: "Prompt Engineering: Writing Prompts That Work",
  },
  {
    id: "m8-l3",
    slug: "using-ai-for-research",
    moduleId: "m8",
    order: 3,
    titleHt: "Itilize IA pou Rechèch",
    titleFr: "Utiliser l'IA pour la Recherche",
    titleEn: "Using AI for Research",
  },
  {
    id: "m8-l4",
    slug: "ai-for-images",
    moduleId: "m8",
    order: 4,
    titleHt: "IA pou Imaj",
    titleFr: "L'IA pour les Images",
    titleEn: "AI for Images",
  },
  {
    id: "m8-l5",
    slug: "ai-for-video",
    moduleId: "m8",
    order: 5,
    titleHt: "IA pou Videyo",
    titleFr: "L'IA pour la Vidéo",
    titleEn: "AI for Video",
  },
  {
    id: "m8-l6",
    slug: "ai-for-voice",
    moduleId: "m8",
    order: 6,
    titleHt: "IA pou Vwa",
    titleFr: "L'IA pour la Voix",
    titleEn: "AI for Voice",
  },
  {
    id: "m8-l7",
    slug: "building-an-ai-workflow",
    moduleId: "m8",
    order: 7,
    titleHt: "Bati yon Workflow IA",
    titleFr: "Construire un Workflow IA",
    titleEn: "Building an AI Workflow",
  },
  {
    id: "m9-l1",
    slug: "facebook-strategy",
    moduleId: "m9",
    order: 1,
    titleHt: "Estrateji Facebook",
    titleFr: "Stratégie Facebook",
    titleEn: "Facebook Strategy",
  },
  {
    id: "m9-l2",
    slug: "instagram-strategy",
    moduleId: "m9",
    order: 2,
    titleHt: "Estrateji Instagram",
    titleFr: "Stratégie Instagram",
    titleEn: "Instagram Strategy",
  },
  {
    id: "m9-l3",
    slug: "tiktok-strategy",
    moduleId: "m9",
    order: 3,
    titleHt: "Estrateji TikTok",
    titleFr: "Stratégie TikTok",
    titleEn: "TikTok Strategy",
  },
  {
    id: "m9-l4",
    slug: "linkedin-strategy",
    moduleId: "m9",
    order: 4,
    titleHt: "Estrateji LinkedIn",
    titleFr: "Stratégie LinkedIn",
    titleEn: "LinkedIn Strategy",
  },
  {
    id: "m9-l5",
    slug: "x-twitter-strategy",
    moduleId: "m9",
    order: 5,
    titleHt: "Estrateji X (Twitter)",
    titleFr: "Stratégie X (Twitter)",
    titleEn: "X (Twitter) Strategy",
  },
  {
    id: "m9-l6",
    slug: "pinterest-strategy",
    moduleId: "m9",
    order: 6,
    titleHt: "Estrateji Pinterest",
    titleFr: "Stratégie Pinterest",
    titleEn: "Pinterest Strategy",
  },
  {
    id: "m9-l7",
    slug: "whatsapp-business-strategy",
    moduleId: "m9",
    order: 7,
    titleHt: "Estrateji WhatsApp Business",
    titleFr: "Stratégie WhatsApp Business",
    titleEn: "WhatsApp Business Strategy",
  },
  {
    id: "m9-l8",
    slug: "youtube-channel-strategy",
    moduleId: "m9",
    order: 8,
    titleHt: "Estrateji Chanèl YouTube",
    titleFr: "Stratégie de Chaîne YouTube",
    titleEn: "YouTube Channel Strategy",
  },
];

export function getDominateDigitalLesson(slug: string) {
  return dominateDigitalLessons.find((lesson) => lesson.slug === slug);
}
