import type { CourseLesson } from "@/content/dominate-digital/schema";

/**
 * Real lessons for the modules that have a built simulator so far. Slugs
 * here must exactly match the MOD<n>_LESSON_SLUGS array inside that
 * module's HTML file (public/academy/digital-marketing-ai/module-<n>.html)
 * -- that file writes these same slugs into the shared completed-lessons
 * key once the module is finished, and this list is what the course page
 * and resume card use to compute progress and the next lesson to resume.
 */
export const dominateDigitalLessons: CourseLesson[] = [
  {
    id: "m1-l1",
    slug: "what-is-digital-marketing",
    moduleId: "m1",
    order: 1,
    titleHt: "Kisa Maketing Dijital Ye?",
    titleFr: "Qu'est-ce que le Marketing Digital ?",
    titleEn: "What Is Digital Marketing?",
  },
  {
    id: "m1-l2",
    slug: "digital-vs-traditional-marketing",
    moduleId: "m1",
    order: 2,
    titleHt: "Maketing Dijital kont Maketing Tradisyonèl",
    titleFr: "Marketing Digital vs. Traditionnel",
    titleEn: "Digital vs. Traditional Marketing",
  },
  {
    id: "m1-l3",
    slug: "the-customer-journey",
    moduleId: "m1",
    order: 3,
    titleHt: "Vwayaj Kliyan an",
    titleFr: "Le Parcours Client",
    titleEn: "The Customer Journey",
  },
  {
    id: "m1-l4",
    slug: "the-marketing-funnel",
    moduleId: "m1",
    order: 4,
    titleHt: "Antonwa Maketing an",
    titleFr: "L'Entonnoir de Marketing",
    titleEn: "The Marketing Funnel",
  },
  {
    id: "m1-l5",
    slug: "understanding-value",
    moduleId: "m1",
    order: 5,
    titleHt: "Konprann Valè",
    titleFr: "Comprendre la Valeur",
    titleEn: "Understanding Value",
  },
  {
    id: "m1-l6",
    slug: "myths-about-digital-marketing",
    moduleId: "m1",
    order: 6,
    titleHt: "Manti Yo Di sou Maketing Dijital",
    titleFr: "Mythes sur le Marketing Digital",
    titleEn: "Myths About Digital Marketing",
  },
  {
    id: "m1-l7",
    slug: "careers-in-digital-marketing",
    moduleId: "m1",
    order: 7,
    titleHt: "Karyè nan Maketing Dijital",
    titleFr: "Les Métiers du Marketing Digital",
    titleEn: "Careers in Digital Marketing",
  },
  {
    id: "m2-l1",
    slug: "why-people-really-buy",
    moduleId: "m2",
    order: 1,
    titleHt: "Poukisa Moun Achte Vrèman (Emosyon kont Lojik)",
    titleFr: "Pourquoi les Gens Achètent Vraiment (Émotion contre Logique)",
    titleEn: "Why People Really Buy (Emotion vs. Logic)",
  },
  {
    id: "m2-l2",
    slug: "building-trust",
    moduleId: "m2",
    order: 2,
    titleHt: "Bati Konfyans",
    titleFr: "Bâtir la Confiance",
    titleEn: "Building Trust",
  },
  {
    id: "m2-l3",
    slug: "social-proof",
    moduleId: "m2",
    order: 3,
    titleHt: "Prèv Sosyal",
    titleFr: "Preuve Sociale",
    titleEn: "Social Proof",
  },
  {
    id: "m2-l4",
    slug: "scarcity",
    moduleId: "m2",
    order: 4,
    titleHt: "Rarete",
    titleFr: "Rareté",
    titleEn: "Scarcity",
  },
  {
    id: "m2-l5",
    slug: "authority",
    moduleId: "m2",
    order: 5,
    titleHt: "Otorite",
    titleFr: "Autorité",
    titleEn: "Authority",
  },
  {
    id: "m2-l6",
    slug: "reciprocity",
    moduleId: "m2",
    order: 6,
    titleHt: "Reprosite",
    titleFr: "Réciprocité",
    titleEn: "Reciprocity",
  },
  {
    id: "m2-l7",
    slug: "pricing-psychology",
    moduleId: "m2",
    order: 7,
    titleHt: "Sikoloji Pri",
    titleFr: "Psychologie des Prix",
    titleEn: "Pricing Psychology",
  },
  {
    id: "m2-l8",
    slug: "color-psychology",
    moduleId: "m2",
    order: 8,
    titleHt: "Sikoloji Koulè",
    titleFr: "Psychologie des Couleurs",
    titleEn: "Color Psychology",
  },
  {
    id: "m3-l1",
    slug: "naming-your-business",
    moduleId: "m3",
    order: 1,
    titleHt: "Bay Biznis Ou Yon Non",
    titleFr: "Nommer Votre Entreprise",
    titleEn: "Naming Your Business",
  },
  {
    id: "m3-l2",
    slug: "positioning",
    moduleId: "m3",
    order: 2,
    titleHt: "Pozisyone (Sa ki Fè w Diferan)",
    titleFr: "Positionnement (Ce qui Vous Différencie)",
    titleEn: "Positioning (What Makes You Different)",
  },
  {
    id: "m3-l3",
    slug: "logo-design-basics",
    moduleId: "m3",
    order: 3,
    titleHt: "Baz Konsepsyon Logo",
    titleFr: "Les Bases du Design de Logo",
    titleEn: "Logo Design Basics",
  },
  {
    id: "m3-l4",
    slug: "choosing-your-brand-colors",
    moduleId: "m3",
    order: 4,
    titleHt: "Chwazi Koulè Mak Ou",
    titleFr: "Choisir les Couleurs de Votre Marque",
    titleEn: "Choosing Your Brand Colors",
  },
  {
    id: "m3-l5",
    slug: "typography-for-your-brand",
    moduleId: "m3",
    order: 5,
    titleHt: "Tipografi pou Mak Ou",
    titleFr: "Typographie pour Votre Marque",
    titleEn: "Typography for Your Brand",
  },
  {
    id: "m3-l6",
    slug: "brand-voice",
    moduleId: "m3",
    order: 6,
    titleHt: "Vwa Mak Ou",
    titleFr: "Voix de Marque",
    titleEn: "Brand Voice",
  },
  {
    id: "m3-l7",
    slug: "brand-personality",
    moduleId: "m3",
    order: 7,
    titleHt: "Pèsonalite Mak Ou",
    titleFr: "Personnalité de Marque",
    titleEn: "Brand Personality",
  },
  {
    id: "m3-l8",
    slug: "consistency-across-everything",
    moduleId: "m3",
    order: 8,
    titleHt: "Konsistans nan Tout Bagay",
    titleFr: "Cohérence Partout",
    titleEn: "Consistency Across Everything",
  },
];

export function getDominateDigitalLesson(slug: string) {
  return dominateDigitalLessons.find((lesson) => lesson.slug === slug);
}
