export interface ComputerLessonSummary {
  slug: string;
  title: string;
  outcome: string;
  available: boolean;
  moduleNumber: number;
}

export const computerEssentialsLessons: ComputerLessonSummary[] = [
  {
    slug: "welcome-to-computers",
    title: "Welcome to Computers",
    outcome: "See how computers changed the world, and why you can learn this.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "what-is-a-computer",
    title: "What Is a Computer?",
    outcome: "Understand what actually makes something a computer.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "desktop-vs-laptop",
    title: "Desktop vs. Laptop",
    outcome: "Know the real difference and which one fits your life.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "tablet-vs-phone",
    title: "Tablet vs. Phone",
    outcome: "Understand what each device is actually built for.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "windows-vs-mac",
    title: "Windows vs. Mac",
    outcome: "Understand the difference so any computer feels less foreign.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "android-vs-iphone",
    title: "Android vs. iPhone",
    outcome: "Know what's genuinely different between the two systems.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "hardware-vs-software",
    title: "Hardware vs. Software",
    outcome:
      "Tell the physical parts apart from the programs that run on them.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "what-is-an-operating-system",
    title: "What Is an Operating System?",
    outcome: "Understand the one program that controls everything else.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "what-is-the-internet",
    title: "What Is the Internet?",
    outcome: "Understand what actually happens when you go online.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "what-is-the-cloud",
    title: "What Is the Cloud?",
    outcome:
      'Understand where your files really go when they\'re "in the cloud."',
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "digital-vocabulary",
    title: "Digital Vocabulary",
    outcome: "Learn the words you'll hear constantly around computers.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "first-digital-mission",
    title: "Your First Digital Mission",
    outcome: "Combine everything from Module 1 into one real, confident task.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "the-monitor",
    title: "The Monitor",
    outcome: "Know what a monitor does and adjust it with confidence.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "keyboard-basics",
    title: "Keyboard Basics",
    outcome: "Recognize the keys you'll actually use every day.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "mouse-and-trackpad",
    title: "Mouse and Trackpad",
    outcome: "Point, click, and scroll with either a mouse or a trackpad.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "webcam-and-microphone",
    title: "Webcam and Microphone",
    outcome: "Know what lets people see and hear you in a video call.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "speakers-and-sound",
    title: "Speakers and Sound",
    outcome: "Understand how sound gets from your device to your ears.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "usb-and-hdmi",
    title: "USB and HDMI",
    outcome: "Recognize the two ports you'll plug things into most.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "charging-and-power-button",
    title: "Charging and the Power Button",
    outcome: "Charge your device safely and know what the power button does.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "restart-vs-shutdown",
    title: "Restart vs. Shutdown",
    outcome: "Know which one to use and see exactly where to click.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "external-devices",
    title: "External Devices, Printers, and Scanners",
    outcome: "Know what to plug in when you need to print or scan.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "meet-your-computer-mission",
    title: "Meet Your Computer, Mission",
    outcome: "Identify every part of a real computer with confidence.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "the-desktop",
    title: "The Desktop",
    outcome: "Know what the desktop is and how to keep it organized.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "taskbar-dock-and-start-menu",
    title: "Taskbar, Dock, and Start Menu",
    outcome: "Launch apps and see what's running, on any platform.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "finder-and-file-explorer",
    title: "Finder and File Explorer",
    outcome: "Browse your files with the app built for exactly that.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "working-with-windows",
    title: "Working with Windows",
    outcome: "Minimize, maximize, and close windows with confidence.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "right-click-and-drag-drop",
    title: "Right-Click and Drag & Drop",
    outcome: "Use two moves that unlock most of what a computer can do.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "keyboard-shortcuts",
    title: "Keyboard Shortcuts",
    outcome: "Copy, paste, undo, and redo without touching a menu.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "settings-and-personalization",
    title: "Settings and Personalization",
    outcome: "Make your device look and feel the way you want.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "sound-and-notifications",
    title: "Sound and Notifications",
    outcome: "Control volume and stop notifications from overwhelming you.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "screenshots-and-screen-recording",
    title: "Screenshots and Screen Recording",
    outcome: "Capture your screen on any device, the right way.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "typing-accented-characters",
    title: "Typing Accented Characters",
    outcome: "Type é, è, à, and ò without a special keyboard.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "multi-tasking",
    title: "Multi-Tasking",
    outcome: "Switch between apps and use two at once, smoothly.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "using-your-computer-mission",
    title: "Using Your Computer, Mission",
    outcome: "Combine every skill from Module 3 into one confident session.",
    available: true,
    moduleNumber: 3,
  },
];
