export interface ComputerLessonSummary {
  slug: string;
  title: string;
  outcome: string;
  available: boolean;
  moduleNumber: number;
}

export const computerEssentialsLessons: ComputerLessonSummary[] = [
  {
    slug: "welcome-to-computers",
    title: "Welcome to Computers",
    outcome: "See how computers changed the world, and why you can learn this.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "what-is-a-computer",
    title: "What Is a Computer?",
    outcome: "Understand what actually makes something a computer.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "desktop-vs-laptop",
    title: "Desktop vs. Laptop",
    outcome: "Know the real difference and which one fits your life.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "tablet-vs-phone",
    title: "Tablet vs. Phone",
    outcome: "Understand what each device is actually built for.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "windows-vs-mac",
    title: "Windows vs. Mac",
    outcome: "Understand the difference so any computer feels less foreign.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "android-vs-iphone",
    title: "Android vs. iPhone",
    outcome: "Know what's genuinely different between the two systems.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "hardware-vs-software",
    title: "Hardware vs. Software",
    outcome:
      "Tell the physical parts apart from the programs that run on them.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "what-is-an-operating-system",
    title: "What Is an Operating System?",
    outcome: "Understand the one program that controls everything else.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "what-is-the-internet",
    title: "What Is the Internet?",
    outcome: "Understand what actually happens when you go online.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "what-is-the-cloud",
    title: "What Is the Cloud?",
    outcome:
      'Understand where your files really go when they\'re "in the cloud."',
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "digital-vocabulary",
    title: "Digital Vocabulary",
    outcome: "Learn the words you'll hear constantly around computers.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "first-digital-mission",
    title: "Your First Digital Mission",
    outcome: "Combine everything from Module 1 into one real, confident task.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "the-monitor",
    title: "The Monitor",
    outcome: "Know what a monitor does and adjust it with confidence.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "keyboard-basics",
    title: "Keyboard Basics",
    outcome: "Recognize the keys you'll actually use every day.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "mouse-and-trackpad",
    title: "Mouse and Trackpad",
    outcome: "Point, click, and scroll with either a mouse or a trackpad.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "webcam-and-microphone",
    title: "Webcam and Microphone",
    outcome: "Know what lets people see and hear you in a video call.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "speakers-and-sound",
    title: "Speakers and Sound",
    outcome: "Understand how sound gets from your device to your ears.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "usb-and-hdmi",
    title: "USB and HDMI",
    outcome: "Recognize the two ports you'll plug things into most.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "charging-and-power-button",
    title: "Charging and the Power Button",
    outcome: "Charge your device safely and know what the power button does.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "restart-vs-shutdown",
    title: "Restart vs. Shutdown",
    outcome: "Know which one to use and see exactly where to click.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "external-devices",
    title: "External Devices, Printers, and Scanners",
    outcome: "Know what to plug in when you need to print or scan.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "meet-your-computer-mission",
    title: "Meet Your Computer, Mission",
    outcome: "Identify every part of a real computer with confidence.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "the-desktop",
    title: "The Desktop",
    outcome: "Know what the desktop is and how to keep it organized.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "taskbar-dock-and-start-menu",
    title: "Taskbar, Dock, and Start Menu",
    outcome: "Launch apps and see what's running, on any platform.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "finder-and-file-explorer",
    title: "Finder and File Explorer",
    outcome: "Browse your files with the app built for exactly that.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "working-with-windows",
    title: "Working with Windows",
    outcome: "Minimize, maximize, and close windows with confidence.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "right-click-and-drag-drop",
    title: "Right-Click and Drag & Drop",
    outcome: "Use two moves that unlock most of what a computer can do.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "keyboard-shortcuts",
    title: "Keyboard Shortcuts",
    outcome: "Copy, paste, undo, and redo without touching a menu.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "settings-and-personalization",
    title: "Settings and Personalization",
    outcome: "Make your device look and feel the way you want.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "sound-and-notifications",
    title: "Sound and Notifications",
    outcome: "Control volume and stop notifications from overwhelming you.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "screenshots-and-screen-recording",
    title: "Screenshots and Screen Recording",
    outcome: "Capture your screen on any device, the right way.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "typing-accented-characters",
    title: "Typing Accented Characters",
    outcome: "Type é, è, à, and ò without a special keyboard.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "multi-tasking",
    title: "Multi-Tasking",
    outcome: "Switch between apps and use two at once, smoothly.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "using-your-computer-mission",
    title: "Using Your Computer, Mission",
    outcome: "Combine every skill from Module 3 into one confident session.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "what-is-a-file-and-folder",
    title: "What Is a File and Folder?",
    outcome: "Understand the two building blocks of everything you save.",
    available: true,
    moduleNumber: 4,
  },
  {
    slug: "standard-folders",
    title: "The Standard Folders",
    outcome: "Know where Desktop, Downloads, Documents, and more belong.",
    available: true,
    moduleNumber: 4,
  },
  {
    slug: "file-extensions",
    title: "File Extensions",
    outcome: "Read the letters after the dot and know what they mean.",
    available: true,
    moduleNumber: 4,
  },
  {
    slug: "working-with-pdf",
    title: "Working with PDF Files",
    outcome: "Open, read, and understand the most common document format.",
    available: true,
    moduleNumber: 4,
  },
  {
    slug: "rename-copy-move-delete",
    title: "Rename, Copy, Move, Delete",
    outcome: "Manage any file with the four moves you'll use constantly.",
    available: true,
    moduleNumber: 4,
  },
  {
    slug: "recycle-bin-and-restore",
    title: "Recycle Bin, Trash, and Restore",
    outcome: "Delete with confidence, knowing you can undo it.",
    available: true,
    moduleNumber: 4,
  },
  {
    slug: "searching-for-files",
    title: "Searching for Files",
    outcome: "Find any file in seconds without digging through folders.",
    available: true,
    moduleNumber: 4,
  },
  {
    slug: "zip-and-compression",
    title: "ZIP Files and Compression",
    outcome: "Shrink and combine files into one easy-to-send package.",
    available: true,
    moduleNumber: 4,
  },
  {
    slug: "cloud-backup",
    title: "Cloud Backup",
    outcome: "Protect your files so a lost or broken device isn't a disaster.",
    available: true,
    moduleNumber: 4,
  },
  {
    slug: "files-and-folders-mission",
    title: "Files & Folders, Mission",
    outcome: "Organize, find, and protect your files with real confidence.",
    available: true,
    moduleNumber: 4,
  },
  {
    slug: "wifi-and-connecting",
    title: "Wi-Fi and Connecting",
    outcome: "Connect any device to the internet with confidence.",
    available: true,
    moduleNumber: 5,
  },
  {
    slug: "browser-basics",
    title: "Browser Basics",
    outcome: "Understand the app that opens the entire internet for you.",
    available: true,
    moduleNumber: 5,
  },
  {
    slug: "search-engines-and-the-address-bar",
    title: "Search Engines and the Address Bar",
    outcome: "Know the difference between searching and typing a web address.",
    available: true,
    moduleNumber: 5,
  },
  {
    slug: "tabs-and-bookmarks",
    title: "Tabs and Bookmarks",
    outcome: "Keep multiple pages open and save the ones you'll need again.",
    available: true,
    moduleNumber: 5,
  },
  {
    slug: "history-and-cache",
    title: "History and Cache",
    outcome: "Find pages you visited before and speed up slow-loading sites.",
    available: true,
    moduleNumber: 5,
  },
  {
    slug: "cookies-explained",
    title: "Cookies Explained",
    outcome: "Understand the small files that remember you across visits.",
    available: true,
    moduleNumber: 5,
  },
  {
    slug: "incognito-mode",
    title: "Incognito and Private Browsing",
    outcome: "Browse without saving history on a shared or public device.",
    available: true,
    moduleNumber: 5,
  },
  {
    slug: "links-and-qr-codes",
    title: "Links and QR Codes",
    outcome: "Follow links and scan codes safely, every time.",
    available: true,
    moduleNumber: 5,
  },
  {
    slug: "downloads-and-uploads",
    title: "Downloads and Uploads",
    outcome: "Move files between the internet and your device with confidence.",
    available: true,
    moduleNumber: 5,
  },
  {
    slug: "data-usage-awareness",
    title: "Data Usage Awareness",
    outcome:
      "Know the difference between Wi-Fi and cellular data, and track your usage.",
    available: true,
    moduleNumber: 5,
  },
  {
    slug: "internet-mastery-mission",
    title: "Internet Mastery, Mission",
    outcome: "Browse, search, and use the internet safely and efficiently.",
    available: true,
    moduleNumber: 5,
  },
  {
    slug: "what-is-email",
    title: "What Is Email?",
    outcome: "Understand what email actually is and why you need it.",
    available: true,
    moduleNumber: 6,
  },
  {
    slug: "creating-a-gmail-account",
    title: "Creating a Gmail Account",
    outcome: "Set up your own free email address, step by step.",
    available: true,
    moduleNumber: 6,
  },
  {
    slug: "inbox-and-composing",
    title: "Inbox and Composing",
    outcome: "Read what's waiting for you and write your first email.",
    available: true,
    moduleNumber: 6,
  },
  {
    slug: "reply-reply-all-forward",
    title: "Reply, Reply All, and Forward",
    outcome: "Respond to email the right way, every time.",
    available: true,
    moduleNumber: 6,
  },
  {
    slug: "email-attachments",
    title: "Email Attachments",
    outcome: "Send and open files without ever worrying you did it wrong.",
    available: true,
    moduleNumber: 6,
  },
  {
    slug: "folders-and-labels",
    title: "Folders and Labels",
    outcome: "Keep a busy inbox organized without losing anything.",
    available: true,
    moduleNumber: 6,
  },
  {
    slug: "spam-and-trash",
    title: "Spam and Trash",
    outcome: "Know where unwanted and deleted email actually goes.",
    available: true,
    moduleNumber: 6,
  },
  {
    slug: "searching-your-email",
    title: "Searching Your Email",
    outcome: "Find any email in seconds, even from years ago.",
    available: true,
    moduleNumber: 6,
  },
  {
    slug: "writing-professional-emails",
    title: "Writing Professional Emails",
    outcome: "Sound clear and confident in any email you send.",
    available: true,
    moduleNumber: 6,
  },
  {
    slug: "recognizing-email-scams",
    title: "Recognizing Email Scams",
    outcome: "Spot a fake or dangerous email before it costs you anything.",
    available: true,
    moduleNumber: 6,
  },
  {
    slug: "email-mastery-mission",
    title: "Email Mastery, Mission",
    outcome: "Set up and use email like a confident professional.",
    available: true,
    moduleNumber: 6,
  },
  {
    slug: "installing-and-uninstalling-apps",
    title: "Installing and Uninstalling Apps",
    outcome: "Add or remove apps and programs on any device, safely.",
    available: true,
    moduleNumber: 7,
  },
  {
    slug: "managing-storage",
    title: "Managing Storage",
    outcome: "Know what's filling up your device and how to free space.",
    available: true,
    moduleNumber: 7,
  },
  {
    slug: "photos-and-your-gallery",
    title: "Photos and Your Gallery",
    outcome: "Find, organize, and share the photos already on your phone.",
    available: true,
    moduleNumber: 7,
  },
  {
    slug: "messages-and-calls",
    title: "Messages and Calls",
    outcome: "Text and call with confidence on any phone.",
    available: true,
    moduleNumber: 7,
  },
  {
    slug: "managing-contacts",
    title: "Managing Contacts",
    outcome: "Save, find, and organize the people you reach out to.",
    available: true,
    moduleNumber: 7,
  },
  {
    slug: "software-updates",
    title: "Software Updates",
    outcome: "Know why updates matter and how to install them safely.",
    available: true,
    moduleNumber: 7,
  },
  {
    slug: "bluetooth-basics",
    title: "Bluetooth Basics",
    outcome: "Connect headphones, speakers, and other devices wirelessly.",
    available: true,
    moduleNumber: 7,
  },
  {
    slug: "mobile-hotspot",
    title: "Mobile Hotspot",
    outcome:
      "Share your phone's internet with another device when you need to.",
    available: true,
    moduleNumber: 7,
  },
  {
    slug: "settings-tour",
    title: "A Tour of Settings",
    outcome: "Find your way around the app that controls everything else.",
    available: true,
    moduleNumber: 7,
  },
  {
    slug: "file-sharing-between-devices",
    title: "File Sharing Between Devices",
    outcome: "Send a photo or file to someone nearby without email or data.",
    available: true,
    moduleNumber: 7,
  },
  {
    slug: "mobile-backups",
    title: "Mobile Backups",
    outcome: "Protect everything on your phone in case it's lost or damaged.",
    available: true,
    moduleNumber: 7,
  },
  {
    slug: "mobile-devices-mission",
    title: "Mobile Devices, Mission",
    outcome: "Get the most out of your Android or iPhone every day.",
    available: true,
    moduleNumber: 7,
  },
  {
    slug: "google-drive",
    title: "Google Drive",
    outcome: "Store and share any file, free, from anywhere.",
    available: true,
    moduleNumber: 8,
  },
  {
    slug: "google-docs",
    title: "Google Docs",
    outcome: "Write and share documents that save themselves.",
    available: true,
    moduleNumber: 8,
  },
  {
    slug: "google-sheets",
    title: "Google Sheets",
    outcome: "Track numbers and lists in a shareable spreadsheet.",
    available: true,
    moduleNumber: 8,
  },
  {
    slug: "google-slides",
    title: "Google Slides",
    outcome: "Build a presentation you can show from any device.",
    available: true,
    moduleNumber: 8,
  },
  {
    slug: "google-calendar",
    title: "Google Calendar",
    outcome: "Schedule events and never miss an appointment again.",
    available: true,
    moduleNumber: 8,
  },
  {
    slug: "google-maps",
    title: "Google Maps",
    outcome: "Find any place and get there with confidence.",
    available: true,
    moduleNumber: 8,
  },
  {
    slug: "google-photos",
    title: "Google Photos",
    outcome: "Back up every photo automatically and find any of them fast.",
    available: true,
    moduleNumber: 8,
  },
  {
    slug: "google-translate",
    title: "Google Translate",
    outcome: "Understand and communicate across any language barrier.",
    available: true,
    moduleNumber: 8,
  },
  {
    slug: "google-meet",
    title: "Google Meet",
    outcome: "Join and host video calls with confidence.",
    available: true,
    moduleNumber: 8,
  },
  {
    slug: "google-keep",
    title: "Google Keep",
    outcome: "Capture quick notes and lists you'll actually find again.",
    available: true,
    moduleNumber: 8,
  },
  {
    slug: "google-ecosystem-mission",
    title: "Google Ecosystem, Mission",
    outcome: "Use Gmail, Drive, Docs, and the rest of Google's everyday tools.",
    available: true,
    moduleNumber: 8,
  },
];
