export interface EnglishLessonSummary {
  slug: string;
  title: string;
  outcome: string;
  available: boolean;
  moduleNumber: number;
}

export const englishLevelOneLessons: EnglishLessonSummary[] = [
  {
    slug: "hello-and-goodbye",
    title: "Byenveni! (Welcome)",
    outcome: "Greet someone and understand how English sentences work.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "my-name-is",
    title: "My Name Is…",
    outcome: "Introduce yourself and ask another person’s name.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "please-thank-you-yes-no",
    title: "Please, Thank You, Yes, and No",
    outcome: "Use four essential words naturally and politely.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "english-alphabet",
    title: "Alfabè a (The Alphabet)",
    outcome: "Know the letter names and when to use capitals.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "letter-sounds",
    title: "Letters and Their Sounds",
    outcome: "Hear and repeat common English letter sounds.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "pronunciation-basics",
    title: "Your First Pronunciation Tools",
    outcome: "Notice mouth position, rhythm, and sounds without fear.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "most-useful-words",
    title: "Words You Will Use Every Day",
    outcome: "Recognize and use a small set of high-value English words.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "i-am",
    title: "I Am…",
    outcome: "Say who you are and how you feel.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "i-have",
    title: "I Have…",
    outcome: "Talk simply about what you have.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "simple-questions",
    title: "Your First Questions",
    outcome: "Ask and answer a few useful questions.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "first-conversation-mission",
    title: "Your First Conversation",
    outcome:
      "Combine greetings, an introduction, and a question in one mission.",
    available: true,
    moduleNumber: 1,
  },
  {
    slug: "am-is-are",
    title: "Am, Is, Are",
    outcome: "Match the right form of to be to every pronoun.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "to-be-contractions",
    title: "A Shorter Way — Contractions",
    outcome: "Use I'm, you're, and he's naturally in conversation.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "to-be-negatives",
    title: "I Am Not… — Negatives",
    outcome: "Say what is not true using am not, isn't, and aren't.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "to-be-questions",
    title: "Are You…? — Questions",
    outcome: "Ask and answer simple yes/no questions with to be.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "describing-people",
    title: "Describing People",
    outcome: "Describe someone's height, character, and personality.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "describing-feelings",
    title: "Describing Feelings",
    outcome: "Express how you feel using to be.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "describing-places-things",
    title: "Describing Places and Things",
    outcome: "Describe a place or object with to be and an adjective.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "talking-about-weather",
    title: "Talking About the Weather",
    outcome: "Talk about the weather using It is.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "jobs-and-family",
    title: "Jobs and Family",
    outcome: "Talk about someone's job or your family relationships.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "to-be-mission",
    title: "Describe Your World",
    outcome: "Combine everything from Module 2 into one real description.",
    available: true,
    moduleNumber: 2,
  },
  {
    slug: "have-and-has",
    title: "Have and Has",
    outcome: "Match the right form of to have to every pronoun.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "have-contractions",
    title: "Contractions with Have",
    outcome: "Use I've, you've, and he's got naturally.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "have-questions",
    title: "Do You Have…?",
    outcome: "Ask and answer questions with have using do and does.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "have-negatives",
    title: "I Don't Have",
    outcome: "Say what you don't have using don't and doesn't.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "talking-about-had",
    title: "Had — Talking About the Past",
    outcome: "Use had to talk about what you used to have.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "have-family",
    title: "Your Family",
    outcome: "Talk about how many family members you have.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "have-money",
    title: "Talking About Money",
    outcome: "Talk about money you have or need using have.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "have-ideas",
    title: "Sharing Ideas",
    outcome: "Share an idea, plan, or question using have.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "have-problems",
    title: "Talking About Problems",
    outcome: "Describe a problem or ache using have.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "have-mission",
    title: "What You Have",
    outcome: "Combine everything from Module 3 into one real description.",
    available: true,
    moduleNumber: 3,
  },
  {
    slug: "days-of-the-week",
    title: "Days of the Week",
    outcome: "Name the seven days and talk about your weekly schedule.",
    available: true,
    moduleNumber: 4,
  },
  {
    slug: "my-daily-routine",
    title: "My Daily Routine",
    outcome: "Describe what you do from morning to night.",
    available: true,
    moduleNumber: 4,
  },
  {
    slug: "around-the-house",
    title: "Around the House",
    outcome: "Name the rooms of a house and what happens in each.",
    available: true,
    moduleNumber: 4,
  },
  {
    slug: "things-in-the-house",
    title: "Things in the House",
    outcome: "Describe what's in a room using there is and there are.",
    available: true,
    moduleNumber: 4,
  },
  {
    slug: "my-family-vocabulary",
    title: "My Extended Family",
    outcome: "Name extended family members beyond parents and siblings.",
    available: true,
    moduleNumber: 4,
  },
  {
    slug: "friends-and-neighbors",
    title: "Friends and Neighbors",
    outcome: "Talk about the people around you who aren't family.",
    available: true,
    moduleNumber: 4,
  },
  {
    slug: "pets-and-animals",
    title: "Pets and Animals",
    outcome: "Talk about pets using have and simple descriptions.",
    available: true,
    moduleNumber: 4,
  },
  {
    slug: "daily-life-mission",
    title: "A Day in My Life",
    outcome: "Tell the story of a full day using everything from Module 4.",
    available: true,
    moduleNumber: 4,
  },
  {
    slug: "who-questions",
    title: "Who — Asking About People",
    outcome: "Ask who someone is or who did something.",
    available: true,
    moduleNumber: 5,
  },
  {
    slug: "when-questions",
    title: "When — Asking About Time",
    outcome: "Ask when something happens using when.",
    available: true,
    moduleNumber: 5,
  },
  {
    slug: "why-questions",
    title: "Why — Asking For Reasons",
    outcome: "Ask why and answer using because.",
    available: true,
    moduleNumber: 5,
  },
  {
    slug: "which-questions",
    title: "Which — Choosing Between Options",
    outcome: "Ask which when choosing between specific options.",
    available: true,
    moduleNumber: 5,
  },
  {
    slug: "whose-questions",
    title: "Whose — Asking About Ownership",
    outcome: "Ask whose something is without confusing it with who's.",
    available: true,
    moduleNumber: 5,
  },
  {
    slug: "how-questions",
    title: "How — Asking About Manner",
    outcome: "Ask how someone is or how something is done.",
    available: true,
    moduleNumber: 5,
  },
  {
    slug: "how-many-questions",
    title: "How Many — Counting Things",
    outcome: "Ask how many for things you can count.",
    available: true,
    moduleNumber: 5,
  },
  {
    slug: "how-much-questions",
    title: "How Much — Amount and Price",
    outcome: "Ask how much for price and things you can't count.",
    available: true,
    moduleNumber: 5,
  },
  {
    slug: "questions-mission",
    title: "Ask Me Anything",
    outcome:
      "Combine every question word from Module 5 in a real conversation.",
    available: true,
    moduleNumber: 5,
  },
  {
    slug: "action-verbs-conjugation",
    title: "Action Verbs and -s/-es",
    outcome: "Know when to add -s or -es to an action verb.",
    available: true,
    moduleNumber: 6,
  },
  {
    slug: "go-and-come",
    title: "Go and Come",
    outcome: "Use go and come to talk about movement and direction.",
    available: true,
    moduleNumber: 6,
  },
  {
    slug: "eat-drink-sleep",
    title: "Eat, Drink, and Sleep",
    outcome: "Talk about daily needs using eat, drink, and sleep.",
    available: true,
    moduleNumber: 6,
  },
  {
    slug: "walk-and-run",
    title: "Walk and Run",
    outcome: "Describe moving on foot, slow or fast.",
    available: true,
    moduleNumber: 6,
  },
  {
    slug: "work-and-study",
    title: "Work and Study",
    outcome: "Talk about work and learning using work and study.",
    available: true,
    moduleNumber: 6,
  },
  {
    slug: "play-watch-listen",
    title: "Play, Watch, and Listen",
    outcome: "Talk about free time using play, watch, and listen.",
    available: true,
    moduleNumber: 6,
  },
  {
    slug: "buy-and-sell",
    title: "Buy and Sell",
    outcome: "Talk about shopping and trading using buy and sell.",
    available: true,
    moduleNumber: 6,
  },
  {
    slug: "cook-wash-clean",
    title: "Cook, Wash, and Clean",
    outcome: "Talk about housework using cook, wash, and clean.",
    available: true,
    moduleNumber: 6,
  },
  {
    slug: "action-verbs-mission",
    title: "A Day of Action",
    outcome: "Combine action verbs from Module 6 into one active story.",
    available: true,
    moduleNumber: 6,
  },
  {
    slug: "do-does-did",
    title: "Do, Does, and Did",
    outcome: "Use do and does correctly, and did for the past.",
    available: true,
    moduleNumber: 7,
  },
  {
    slug: "make-and-take",
    title: "Make and Take",
    outcome: "Use make and take in common everyday phrases.",
    available: true,
    moduleNumber: 7,
  },
  {
    slug: "put-and-get",
    title: "Put and Get",
    outcome: "Use put and get to place and receive things.",
    available: true,
    moduleNumber: 7,
  },
  {
    slug: "give-and-bring",
    title: "Give and Bring",
    outcome: "Use give and bring to talk about sharing and carrying things.",
    available: true,
    moduleNumber: 7,
  },
  {
    slug: "become-and-find",
    title: "Become and Find",
    outcome: "Use become for change and find for discovery.",
    available: true,
    moduleNumber: 7,
  },
  {
    slug: "keep-and-leave",
    title: "Keep and Leave",
    outcome: "Use keep to hold onto things and leave to depart.",
    available: true,
    moduleNumber: 7,
  },
  {
    slug: "power-verbs-mission",
    title: "Everyday Power Verbs",
    outcome: "Combine every verb from Module 7 into one daily story.",
    available: true,
    moduleNumber: 7,
  },
  {
    slug: "meeting-someone",
    title: "Meeting Someone",
    outcome: "Start, carry, and end a full first conversation.",
    available: true,
    moduleNumber: 8,
  },
  {
    slug: "at-the-restaurant",
    title: "At the Restaurant",
    outcome: "Order food and ask for the check with confidence.",
    available: true,
    moduleNumber: 8,
  },
  {
    slug: "at-the-store",
    title: "At the Store",
    outcome: "Ask about size, price, and pay for something in a store.",
    available: true,
    moduleNumber: 8,
  },
  {
    slug: "taxi-and-airport",
    title: "Taxi and Airport",
    outcome: "Handle a taxi ride and basic airport situations.",
    available: true,
    moduleNumber: 8,
  },
  {
    slug: "at-the-doctor",
    title: "At the Doctor",
    outcome: "Describe symptoms and understand a doctor's questions.",
    available: true,
    moduleNumber: 8,
  },
  {
    slug: "bank-and-hotel",
    title: "Bank and Hotel",
    outcome: "Handle a bank visit and a hotel check-in.",
    available: true,
    moduleNumber: 8,
  },
  {
    slug: "phone-call",
    title: "A Phone Call",
    outcome: "Start, hold, and end a phone call politely.",
    available: true,
    moduleNumber: 8,
  },
  {
    slug: "whatsapp-and-email",
    title: "WhatsApp and Email",
    outcome: "Write a casual WhatsApp message and a formal email.",
    available: true,
    moduleNumber: 8,
  },
  {
    slug: "conversations-mission",
    title: "Any Situation",
    outcome: "Handle an unexpected real-life conversation with confidence.",
    available: true,
    moduleNumber: 8,
  },
  {
    slug: "i-like-pattern",
    title: "I Like...",
    outcome: "Say what you like and don't like.",
    available: true,
    moduleNumber: 9,
  },
  {
    slug: "can-i-pattern",
    title: "Can I...?",
    outcome: "Ask for permission politely.",
    available: true,
    moduleNumber: 9,
  },
  {
    slug: "would-you-pattern",
    title: "Would You...?",
    outcome: "Make polite requests and offers.",
    available: true,
    moduleNumber: 9,
  },
  {
    slug: "there-is-there-are-pattern",
    title: "There Is / There Are",
    outcome: "Describe what exists in any situation, not just a house.",
    available: true,
    moduleNumber: 9,
  },
  {
    slug: "want-and-would-like-pattern",
    title: "I Want / I'd Like",
    outcome: "Choose between direct and polite ways to ask for something.",
    available: true,
    moduleNumber: 9,
  },
  {
    slug: "going-to-pattern",
    title: "I'm Going To...",
    outcome: "Talk about future plans using going to.",
    available: true,
    moduleNumber: 9,
  },
  {
    slug: "i-need-pattern",
    title: "I Need...",
    outcome: "Express a real need, stronger than a want.",
    available: true,
    moduleNumber: 9,
  },
  {
    slug: "i-dont-pattern",
    title: "I Don't...",
    outcome: "Use I don't for common everyday negatives.",
    available: true,
    moduleNumber: 9,
  },
  {
    slug: "patterns-mission",
    title: "Building Blocks",
    outcome: "Combine every pattern from Module 9 into natural sentences.",
    available: true,
    moduleNumber: 9,
  },
  {
    slug: "apostrophe-confusion",
    title: "Your/You're, Its/It's, There/Their/They're",
    outcome: "Never confuse a possessive with a contraction again.",
    available: true,
    moduleNumber: 10,
  },
  {
    slug: "to-too-two",
    title: "To, Too, and Two",
    outcome: "Use these three homophones correctly every time.",
    available: true,
    moduleNumber: 10,
  },
  {
    slug: "then-vs-than",
    title: "Then vs. Than",
    outcome: "Know when to use then for time and than for comparisons.",
    available: true,
    moduleNumber: 10,
  },
  {
    slug: "look-see-watch",
    title: "Look, See, and Watch",
    outcome: "Choose the right verb for how you're using your eyes.",
    available: true,
    moduleNumber: 10,
  },
  {
    slug: "say-tell-speak-talk",
    title: "Say, Tell, Speak, and Talk",
    outcome: "Use the right communication verb in the right situation.",
    available: true,
    moduleNumber: 10,
  },
  {
    slug: "listen-vs-hear",
    title: "Listen vs. Hear",
    outcome: "Know the difference between hearing and paying attention.",
    available: true,
    moduleNumber: 10,
  },
  {
    slug: "much-many-few-little",
    title: "Much, Many, Few, and Little",
    outcome: "Match quantity words to countable and uncountable nouns.",
    available: true,
    moduleNumber: 10,
  },
  {
    slug: "borrow-lend-bring-take",
    title: "Borrow/Lend, Bring/Take",
    outcome: "Use the right verb for the direction of an exchange.",
    available: true,
    moduleNumber: 10,
  },
  {
    slug: "teach-learn-job-work",
    title: "Teach/Learn, Job/Work",
    outcome: "Untangle two more common Haitian Creole speaker mix-ups.",
    available: true,
    moduleNumber: 10,
  },
  {
    slug: "confusing-english-mission",
    title: "Make the Difference",
    outcome: "Use every confusing pair from Module 10 correctly in context.",
    available: true,
    moduleNumber: 10,
  },
  {
    slug: "look-up-for-after",
    title: "Look Up, Look For, Look After",
    outcome: "Use three different meanings of look with a particle.",
    available: true,
    moduleNumber: 11,
  },
  {
    slug: "get-up-out-in",
    title: "Get Up, Get Out, Get In",
    outcome: "Describe precise movements using get with a particle.",
    available: true,
    moduleNumber: 11,
  },
  {
    slug: "put-on-away",
    title: "Put On, Put Away",
    outcome: "Talk about wearing and storing things with put.",
    available: true,
    moduleNumber: 11,
  },
  {
    slug: "come-back-go-out",
    title: "Come Back, Go Out",
    outcome: "Talk about returning and leaving somewhere.",
    available: true,
    moduleNumber: 11,
  },
  {
    slug: "turn-on-off",
    title: "Turn On, Turn Off",
    outcome: "Talk about switching devices on and off.",
    available: true,
    moduleNumber: 11,
  },
  {
    slug: "phrasal-verbs-mission",
    title: "Phrasal Verbs in Action",
    outcome: "Combine every phrasal verb from Module 11 into one story.",
    available: true,
    moduleNumber: 11,
  },
];
